# config.yaml
model:
  base_model: "deepseek-ai/deepseek-llm-7b-base"
  dropout: 0.1
  lora:
    r: 64
    alpha: 64

training:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 2
  num_train_epochs: 3
  learning_rate: 5e-5
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.1
  save_strategy: "epoch"
  output_dir: "outputs/checkpoints/full_precision/"
  logging_steps: 25
  seed: 42
  max_length: 1536

cache:
  hf_home: "data/.hf_home"
  datasets_cache: "data/.hf_home/datasets"

wandb:
  project: "deepseek-gsm8k-finetuned-v2"
  entity: "egulotty-boston-university"
